name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"    # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate classic metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: chenfeng-huang
          template: classic
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          output_action: commit
          committer_branch: main
          committer_message: "chore: update classic metrics"

          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_introduction_about: |
            Hi there, my name is Chenfeng Huang.  
            I was born in Chengdu, China ðŸ‡¨ðŸ‡³ and now study Applied Data Science at USC.  
            My current research focuses on Time Series OOD Generalization.  

            I am also actively competing in Kaggle challenges at the Expert level  
            ðŸ”— [Kaggle Profile](https://www.kaggle.com/alrickh)  

            Beyond data science, I am passionate about coffee brewing.  
            Check out my coffee notes here:  
            ðŸ”— [Homepage](https://chenfenghuang.info)
